### PR TITLE
release: highlights of v0.0.5

### PR DESCRIPTION
**Pull request by bartoszmajsak**

### CODE REVIEW

**Comment by alien-ike** [comment]
#### ⚠ Failed validating PR content

Tag v0.0.4 already exists!

**Comment by alien-ike** [comment]
#### ⚠ Failed validating release Pull Request

Tag v0.0.4 already exists!

**Comment by alien-ike** [comment]
#### ⚠ Failed validating release Pull Request

Tag v0.0.4 already exists!

**Comment by alien-ike** [comment]
#### ⚠ Failed validating release Pull Request

Version `v0.0.4` already exists!

**Comment by bartoszmajsak** [comment]
@alien-ike

**Pull request closed without merging**
